### ISSUE TITLE
Add coverage reports to builds

### ISSUE THREAD

**Issue by asgrim** [SeidenGroup/doctrine-dbal-ibmi#11]
Currently `xdebug` is not available on the [build server](http://idevusr016.idevcloud.com:9090/job/doctrine-dbal-ibmi/), therefore no code coverage reports. These are going to be useful to ensure we are testing at least the base functionality.

**Comment by phansys** [comment]
As the pipeline is [already configured to upload the coverage report](https://github.com/SeidenGroup/doctrine-dbal-ibmi/blob/5203036da8e0dcdcce788ece760c24a949e9d35f/.github/workflows/test.yml#L106-L110), the only missing step is [enabling Codecov](https://app.codecov.io/gh/SeidenGroup/doctrine-dbal-ibmi/new).

**Comment by phansys** [comment]
@NattyNarwhal, I guess we can close this issue as completed.
