### ISSUE TITLE
Enable builds on Pull Requests

### ISSUE THREAD

**Issue by asgrim** [SeidenGroup/doctrine-dbal-ibmi#12]
I've installed the GitHub Pull Request Builder plugin but not managed to configure and get it working yet. This is essential for accepting PRs from the IBM OSS community so contributors can see quick feedback on proposed changes. The PR build status should be updated, and have a link back to the build server so failure logs can be seen etc.

Note: this may need @alanseiden to grant some permissions or configure the webhooks for me as I don't currently have access to the /settings page for this repo.

**Comment by alanseiden** [comment]
@asgrim Let me know what you need.

**Comment by asgrim** [comment]
Might make sense to move this to an organisation (rather than on your user) to allow better access controls, I think that's what'll have to happen eventually. Let's look into it when we meet at ZendCon next week :)

**Comment by alanseiden** [comment]
I was having the same thought, James. Yes, let's look at it together at Zendcon.
