### ISSUE TITLE
[RFC] Review the SQL generated by `DB2IBMiPlatform::doModifyLimitQuery()`

### ISSUE THREAD

**Issue by phansys** [SeidenGroup/doctrine-dbal-ibmi#46]
## Feature Request

Related to #9, #15, #16, #43.

This call 

```php
$sql = 'SELECT * FROM MY_TABLE';

/** @var \DoctrineDbalIbmi\Platform\DB2IBMiPlatform $platform */
$platform->modifyLimitQuery($sql, null, 1));
```

derives in a call to `DB2IBMiPlatform::doModifyLimitQuery()`, which returns a statement like this:

```sql
SELECT DOCTRINE_TBL.* FROM (
    SELECT DOCTRINE_TBL1.*, ROW_NUMBER() OVER() AS DOCTRINE_ROWNUM FROM (
        SELECT * FROM MY_TABLE
    ) DOCTRINE_TBL1
) DOCTRINE_TBL
WHERE
    DOCTRINE_TBL.DOCTRINE_ROWNUM BETWEEN 2 AND 1
```

This statement:
* Produces a 0-row result because the `DOCTRINE_TBL.DOCTRINE_ROWNUM BETWEEN 2 AND 1` clause;
* Adds a `DOCTRINE_ROWNUM` column to the result set;

I'm not familiar with the `LIMIT` / `OFFSET` clauses in DB2, but I think we should find a way to produce more consistent statements here.

**Comment by alanseiden** [comment]
LIMIT and OFFSET were not available at the time, but they are now!
Example here: 
https://gist.github.com/phpdave/efa234a9f4bef331aadb

**Comment by phansys** [comment]
Thank you for the feedback.
I've read about this ([ref](https://www.itjungle.com/2016/01/12/fhg011216-story03/).), but it seems this feature was introduced in **IBM i 7.1 TR11** or **IBM i 7.2 TR3**. I don't know if these are versions nor when they were published. Is safe to change to `LIMIT` / `OFFSET` clauses now, or might we be breaking some BC promise?

**Comment by alanseiden** [comment]
Yes, it's safe to use `LIMIT` / `OFFSET` clauses now. They are well established at this point. The lowest currently supported IBM i version is now 7.3. Here is the IBM i release lifecycle page: https://www.ibm.com/support/pages/release-life-cycle

**Comment by alanseiden** [comment]
I appreciate your care and concern for backward compabitility! I usually feel the same way, but in this case, I believe it is safe to make the change.

**Comment by phansys** [comment]
I've updated #43 based on your suggestion.

Thank you so much!
